name: macOS
on:
  push:
    paths-ignore:
      - 'doc/**'
      - '**/man'
      - '**.md'
      - '**.rdoc'
      - '**/.document'
      - '.*.yml'
  pull_request:
    # Do not use paths-ignore for required status checks
    # https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
  merge_group:

env:
  # GITHUB_PULL_REQUEST_URL are used for commenting test reports in Launchable Github App.
  # https://github.com/launchableinc/cli/blob/v1.80.1/launchable/utils/link.py#L42
  GITHUB_PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
  # The following envs are necessary in Launchable tokenless authentication.
  # https://github.com/launchableinc/cli/blob/v1.80.1/launchable/utils/authentication.py#L20
  # LAUNCHABLE_ORGANIZATION: ${{ github.repository_owner }}
  LAUNCHABLE_ORGANIZATION: foo
  LAUNCHABLE_WORKSPACE: ${{ github.event.repository.name }}
  # https://github.com/launchableinc/cli/blob/v1.80.1/launchable/utils/authentication.py#L71
  GITHUB_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
  # This setting only needs for forked repositories from the ruby/ruby.
  # LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}
  # TEST_RUN_LAUNCHABLE: ${{ (github.repository == 'ruby/ruby' || (github.repository != 'ruby/ruby' && secrets.LAUNCHABLE_TOKEN)) && true || '' }}

concurrency:
  group: ${{ github.workflow }} / ${{ startsWith(github.event_name, 'pull') && github.ref_name || github.sha }}
  cancel-in-progress: ${{ startsWith(github.event_name, 'pull') }}

permissions:
  contents: read

jobs:
  make:
    strategy:
      matrix:
        test_task: ['check']
        test_opts: ['']
        run_launchable: ${{ (github.repository == 'ruby/ruby' || (github.repository != 'ruby/ruby' && secrets.LAUNCHABLE_TOKEN)) && [true] || [false] }}
        configure: ['']
        os: ${{ fromJSON(format('["macos-12","macos-13"{0}]', (github.repository == 'ruby/ruby' && ',"macos-arm-oss"' || ''))) }}
        include:
          - test_task: test-all
            test_opts: --repeat-count=2
            run_launchable: ${{ (github.repository == 'ruby/ruby' || (github.repository != 'ruby/ruby' && secrets.LAUNCHABLE_TOKEN)) && true || false }}
            os: ${{ github.repository == 'ruby/ruby' && 'macos-arm-oss' || 'macos-13' }}
          - test_task: test-bundled-gems
            os: ${{ github.repository == 'ruby/ruby' && 'macos-arm-oss' || 'macos-13' }}
      fail-fast: false

    env:
      GITPULLOPTIONS: --no-tags origin ${{ github.ref }}

    runs-on: ${{ matrix.os }}

    if: >-
      ${{!(false
      || contains(github.event.head_commit.message, '[DOC]')
      || contains(github.event.pull_request.title, '[DOC]')
      || contains(github.event.pull_request.labels.*.name, 'Documentation')
      || (github.event_name == 'push' && github.actor == 'dependabot[bot]')
      )}}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: /.github
          # Set fetch-depth: 0 so that Launchable can receive commits information.
          fetch-depth: 0

      - name: Install libraries
        uses: ./.github/actions/setup/macos

      - uses: ./.github/actions/setup/directories
        with:
          srcdir: src
          builddir: build
          makeup: true
          dummy-files: ${{ matrix.test_task == 'check' }}

      - name: Run configure
        run: ../src/configure -C --disable-install-doc ${{ matrix.configure }}

      - run: make prepare-gems
        if: ${{ matrix.test_task == 'test-bundled-gems' }}

      - run: make

      # This setting only needs for forked repositories from the ruby/ruby.
      - name: Set token for forked repositories
        run: |
          echo "LAUNCHABLE_TOKEN=${{ secrets.LAUNCHABLE_TOKEN }}" >> "$GITHUB_ENV"
        if: ${{ github.repository != 'ruby/ruby' && matrix.run_launchable }}

      # Launchable CLI requires Python and Java
      # https://www.launchableinc.com/docs/resources/cli-reference/
      - name: Set up Python
        uses: actions/setup-python@871daa956ca9ea99f3c3e30acb424b7960676734 # v5.0.0
        with:
          python-version: "3.10"
        if: matrix.run_launchable

      - name: Set up Java
        uses: actions/setup-java@7a445ee88d4e23b52c33fdc7601e40278616c7f8 # v4.0.0
        with:
          distribution: 'temurin'
          java-version: '17'
        if: matrix.run_launchable

      - name: Set up Launchable
        id: setup_launchable
        run: |
          set -ex
          pip install launchable
          launchable verify
          launchable record build --name ${GITHUB_PR_HEAD_SHA}
          : # To avoid file name conflicts, we use a random number here as a ID.
          reports=${GITHUB_RUN_ID}_${RANDOM}.json
          echo "TEST_LAUNCHABLE_REPORTS=${reports}" >> "$GITHUB_ENV"
          echo "TEST_LAUNCHABLE_OPTS=--launchable-test-reports=${reports}" >> "$GITHUB_ENV"
        if: matrix.run_launchable

      - name: make ${{ matrix.test_task }}
        run: |
          make -s ${{ matrix.test_task }} TESTS="${{ matrix.test_opts || '' }} ${TEST_LAUNCHABLE_OPTS}" ${TESTS:+TESTS=`echo "$TESTS" | sed 's| |$$/ -n!/|g;s|^|-n!/|;s|$|$$/|'`}
        timeout-minutes: 60
        env:
          RUBY_TESTOPTS: '-q --tty=no'
          TESTS: ${{ matrix.test_task == 'check' && matrix.skipped_tests || '' }}
          TEST_BUNDLED_GEMS_ALLOW_FAILURES: 'minitest,test-unit,debug,bigdecimal,drb,typeprof'
          PRECHECK_BUNDLED_GEMS: 'no'

      - name: make skipped tests
        run: |
          make -s test-all TESTS=`echo "$TESTS" | sed 's| |$$/ -n/|g;s|^|-n/|;s|$|$$/|'`
        env:
          GNUMAKEFLAGS: ''
          RUBY_TESTOPTS: '-v --tty=no'
          TESTS: ${{ matrix.skipped_tests }}
          PRECHECK_BUNDLED_GEMS: 'no'
        if: ${{ matrix.test_task == 'check' && matrix.skipped_tests != '' }}
        continue-on-error: ${{ matrix.continue-on-skipped_tests || false }}

      - name: Launchable - record tests
        run: launchable record tests --flavor os=${{ matrix.os }} --flavor test_task=${{ matrix.test_task }} raw $TEST_LAUNCHABLE_REPORTS
        if: ${{ always() && matrix.run_launchable }}

      - uses: ./.github/actions/slack
        with:
          label: ${{ matrix.os }} / ${{ matrix.test_task }} ${{ matrix.configure }}
          SLACK_WEBHOOK_URL: ${{ secrets.SIMPLER_ALERTS_URL }} # ruby-lang slack: ruby/simpler-alerts-bot
        if: ${{ failure() }}

  result:
    if: ${{ always() }}
    name: ${{ github.workflow }} result
    runs-on: macos-latest
    needs: [make]
    steps:
      - run: exit 1
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}

defaults:
  run:
    working-directory: build
